# Generated by Django 4.2.7 on 2025-05-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_assign_default_apps_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='app_name',
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
