# Generated by Django 4.2.7 on 2025-05-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_activitylog_app_name_delete_appaccess'),
    ]

    operations = [

    ]
