# Generated by Django 4.2.7 on 2025-05-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_delete_appaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_access_enabled',
            field=models.BooleanField(default=False, help_text='Allow user to access paid APIs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_daily_limit',
            field=models.IntegerField(default=10, help_text='Maximum API calls per day'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_monthly_limit',
            field=models.IntegerField(default=100, help_text='Maximum API calls per month'),
        ),
    ]
