# Generated by Django 4.2.7 on 2025-05-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='used_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlacesSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_meters', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('place_types', models.JSONField(default=list)),
                ('results', models.JSONField()),
                ('result_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='api_placess_cache_k_3d22ce_idx'), models.Index(fields=['latitude', 'longitude'], name='api_placess_latitud_c10801_idx'), models.Index(fields=['created_at'], name='api_placess_created_cc97c7_idx')],
            },
        ),
    ]
