# Generated by Django 4.2.7 on 2025-04-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storycraft', '0003_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSceneMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire', models.TextField(blank=True, help_text='What does the character want in this scene?', null=True)),
                ('obstacle', models.TextField(blank=True, help_text='What prevents the character from getting what they want?', null=True)),
                ('action', models.TextField(blank=True, help_text='What does the character do about their obstacle?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_motivations', to='storycraft.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_motivations', to='storycraft.scene')),
            ],
            options={
                'verbose_name': 'Character Motivation',
                'verbose_name_plural': 'Character Motivations',
                'unique_together': {('character', 'scene')},
            },
        ),
    ]
