# Generated by Django 4.2.7 on 2025-04-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemascope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarykeycandidate',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_keys', to='schemascope.schemadefinition'),
        ),
        migrations.AlterField(
            model_name='schemachange',
            name='previous_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_changes', to='schemascope.datasource'),
        ),
        migrations.AlterField(
            model_name='schemachange',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='schemascope.datasource'),
        ),
        migrations.AlterField(
            model_name='schemadefinition',
            name='data_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='schemascope.datasource'),
        ),
        migrations.AlterField(
            model_name='schemarelationship',
            name='source_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='schemascope.schemadefinition'),
        ),
        migrations.AlterField(
            model_name='schemarelationship',
            name='target_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='schemascope.schemadefinition'),
        ),
    ]
