# Generated by Django 4.2.7 on 2025-05-12 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_disposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('addition_type', models.CharField(choices=[('new_stock', 'New Stock'), ('manufactured', 'Manufactured'), ('returned', 'Returned Stock'), ('correction', 'Inventory Correction'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='inventory.item')),
            ],
        ),
    ]
